[build]
target = "target_rasp.json"

[target.armv7-unknown-none-eabihf]
linker = "arm-none-eabi-gcc"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]